### ISSUE TITLE
Repo name doesn't allow for "/" paths

### ISSUE THREAD

**Issue by Christoffer-Cortes** [devopshq/artifactory-cleanup#101]
When putting a repo name that is pathed "repo/my/folder" it's specifically not allowed in the init of Repo rules.
In the check function I can see a /api/storage/<repo> request is made and that one works fine using a "/" repo path.
How is one supposed to clean up a sub folder then using this lib?

**Comment by allburov** [comment]
Hi! You should use `IncludePath` and other filters - https://github.com/devopshq/artifactory-cleanup#filters
```yaml
      rules:
        - rule: Repo
          name: "reponame"
        - rule: DeleteOlderThan
          days: 7
        - rule: IncludePath
          masks: "*my/folder*"
```
