### ISSUE TITLE
Possibility to use Regex

### ISSUE THREAD

**Issue by BlazeF35** [devopshq/artifactory-cleanup#111]
It would be interesting if there was the possibility of using regex when configuring a rule in the artifactory-cleanup.yaml file, as in the example below:
       
```
 - rule: IncludeFilename
  masks: 
   - "*/production-[0-9]+"
   - "*.develop-[0-9]+"
```

That way I believe you would have more control over what you want to look for in a repository.

**Comment by felipecrs** [comment]
That would be super helpful for deleting draft PR docker images, for example:

```yaml
- rule: IncludeFilename
  masks: 
    - ".*/pr-[0-9]+"
```

**Comment by allburov** [comment]
Doesn't it works for your cases? It includes `[0-9]+` as well
```yaml
- rule: IncludeFilename
  masks: 
   - "*production-*"
   - "*develop-*"
```

Feel free to create a PR for the feature if it doesn't!
