### ISSUE TITLE
Exclude repo while deleting artifacts older than n days

### ISSUE THREAD

**Issue by muhammeddanish** [devopshq/artifactory-cleanup#113]
I am facing a challenge with the artifact deletion process, and I would greatly appreciate some assistance in resolving it. My goal is to delete all artifacts that have been downloaded before 365 days, with the exception of 3 specific repositories. Below is the rule I am attempting to apply:
```
policies:
    - name: Remove docker images from repo-name-here older than 365 days
      rules:
        - rule: DeleteNotUsedSince
          days: 365
        - rule: ExcludePath
          masks:
            - "*repo1/*"
            - "*repo2/*"
            - "*repo3/*"
 ```
Despite trying various combinations for the exclusion rule mentioned above, it seems that the specified repositories are not being excluded from the deletion process. I would be extremely grateful if someone could kindly offer their assistance in resolving this matter. Thank you in advance for your help!
