### ISSUE TITLE
Duplicate manifest in aql

### ISSUE THREAD

**Issue by zhan9san** [devopshq/artifactory-cleanup#135]
If there are two docker rules, there would be a duplicate manifest in aql.

```txt
********************************************************************************
Result AQL Query:
items.find({"$and": [{"repo": {"$eq": "example-docker-preprod-local"}}, {"$or": [{"path": {"$match": "foo/*"}}]}, {"name": {"$match": "manifest.json"}}, {"modified": {"$lt": "2024-01-11"}}, {"name": {"$match": "manifest.json"}}]}).include("*", "property", "stat")
********************************************************************************
```

```yaml
    - name: Delete example-docker-preprod-local/foo/* older than 180 days
      rules:
        - rule: Repo
          name: example-docker-preprod-local
        - rule: IncludeDockerImages
          masks: foo:*
        - rule: DeleteDockerImagesOlderThan
          days: 180
```
