### ISSUE TITLE
Is there a way to match only non-docker images in a docker repository?

### ISSUE THREAD

**Issue by felipecrs** [devopshq/artifactory-cleanup#154]
I have a docker repository where we publish both docker images and generic artifacts.

I was able to cleanup the docker images by applying the docker rules.

But, how do I delete the generic artifacts now (without deleting the docker images), do you have any idea?

I already tried:

```yaml
        - rule: ExcludeDockerImages
          masks:
            - "*"
```

But this causes all artifacts to be excluded from the deletion.

**Comment by felipecrs** [comment]
Ok, found a workaround:

```yaml
        - rule: ExcludeFilename
          masks:
            - "manifest.json"
            - "sha256__*"
```
