### ISSUE TITLE
Unwanted artifacts deleted because stats.remote_downloads not used in AQL queries

### ISSUE THREAD

**Issue by philippe-granet** [devopshq/artifactory-cleanup#156]
I have this rule:
```yaml
    - name: Delete Maven artifacts not used since 90 days
      rules:
        - rule: RepoList
          repos:
            - my-repo
        - rule: DeleteNotUsedSince
          days: 90
```
This generate this AQL query:
`items.find({"$and": [{"$or": [{"repo": {"$eq": "my-repo"}}]}, {"$or": [{"stat.downloaded": {"$lte": "2024-10-10"}}, {"$and": [{"stat.downloads": {"$eq": null}}, {"created": {"$lte": "2024-10-10"}}]}]}]}).include("*", "property", "stat")`

The problem is that I don't query artifacts directly on my Artifactory instance. For security reasons, I query artifacts form a second Artifactory proxy instance , which remotely access artifacts from the first Artifactory instance.

On the first Artifactory instance, `stat.downloaded` attribute is never update, only `stats.remote_downloads` attribute is updated after each download of the artifacts from the second Artifactory proxy instance:
![image](https://github.com/user-attachments/assets/b13e2791-dce5-4f20-be4a-972ef48e1bdc)
