### ISSUE TITLE
FilterByRegexpPath() takes no arguments

### ISSUE THREAD

**Issue by stiwa-wrre** [devopshq/artifactory-cleanup#159]
Used the example from the Docs, with the correct function name (with single quotes, because with the double quotes i get another error):

```
        - rule: FilterByRegexpPath
          path: '\d'
```

```
Failed to initialize rule 'FilterByRegexpPath' in policy 'test'.
FilterByRegexpPath() takes no arguments
```

**Comment by gruselglatz** [comment]
The change in the readme didn't fix the issue in the code:

```
Failed to initialize rule 'FilterByRegexpPath' in policy 'test'.
FilterByRegexpPath() takes no arguments
```

**Comment by stiwa-wrre** [comment]
The change in the readme didn't fix the issue in the code:

```
Failed to initialize rule 'FilterByRegexpPath' in policy 'test'.
FilterByRegexpPath() takes no arguments
```

**Comment by stiwa-wrre** [comment]
Just for a Test took the example from the README:
```
artifactory-cleanup:
  server: https://repository.example.com/artifactory
  # $VAR is auto populated from environment variables
  user: $ARTIFACTORY_USERNAME
  password: $ARTIFACTORY_PASSWORD

  policies:
    - name: test
      rules:
        - rule: Repo
          name: "distribution-local"
        - rule: FilterByRegexpPath
          path: '\d'
```

The error occurs because there's a typo in the FilterByRegexpPath class definition. The initialization method is incorrectly defined as `init` instead of `__init__`. 

Here's what's wrong:
```python
def init(self, path):
    self.path = rf"{path}"
```

Should be:
```python
def __init__(self, path): 
    self.path = rf"{path}"
```

Because of this typo, Python doesn't recognize the proper constructor method, so when you try to create a FilterByRegexpPath instance with arguments, it complains that it takes no arguments. To fix this, simply change `init` to `__init__` and the error will be resolved.
