### ISSUE TITLE
Proposal: YAML format for rules

### ISSUE THREAD

**Issue by allburov** [devopshq/artifactory-cleanup#54]
Engineers who support Artifactory sometimes don't know python but almost everyone is familiar with YAML.

Right now artifactory-cleanup import rules only from YAML, but I think the library is used limited because it requires a bit of knowing how to write python script and be familiar with its syntax.

For me, if I find a useful tool in different language and it's configurable via YAML \ JSON \ TOML - it's fine for me, I use it.
But if I find a tool that requires me to write a few lines of Ruby code to configure it - I'll think twice and try to find another solution.

The basic idea why we used python at the very first step - it gives a lot of comfort for people who know python - IDE suggestions, highlight and flexible mechanism to import from different files 

I think we should move our configuration to YAML format, as follow

------------
**artifactory-cleanup.yaml** (can be changed in CLI)
```yaml
artifactory-cleanup:
  server: https://repo.example.com/artifactory
  # $VAR is auto populated from environment variables
  user: $ARTIFACTORY_USERNAME
  password: $ARTIFACTORY_PASSWORD

  policies:
    - name: Remove all .tmp files older than 7 days
      rules:
        - rule: RepoByMask
          mask: "*.tmp"
        - rule: DeleteOlderThan
          days: 7

    - name: My Docker Cleanup Policies
      rules:
        - rule: RepoByMask
          mask: "docker-*-tmp"
        - rule: DeleteOlderThan
          days: 7

    - name: My Docker Cleanup Policies
      rules:
        - rule: RepoByMask
          mask: "docker-*-tmp"
        - rule: ExcludeDockerImages
          masks:
            - '*:latest'
            - '*:release*'
        - rule: DeleteOlderThan
          days: 7
```
