### ISSUE TITLE
ExcludeDockerImages fails with missing 1 required positional argument: 'masks'

### ISSUE THREAD

**Issue by fuzzmz** [devopshq/artifactory-cleanup#72]
The following config fails with 
```
Check failed for rule 'ExcludeDockerImages' in policy 'Remove docker images, but keep last 10':
check() missing 1 required positional argument: 'masks'
```

Relevant part of `artifactory-cleanup.yaml`
```yaml
  policies:
    - name: Remove docker images, but keep last 10
      rules:
        # Select repo
        - rule: Repo
          name: docker-local
        # Keep these tags for all images
        - rule: ExcludeDockerImages
          masks:
            - "*:latest"
            - "*:release*"
```
