### ISSUE TITLE
Support list for Repo rule

### ISSUE THREAD

**Issue by AlexDaciuk** [devopshq/artifactory-cleanup#75]
Hi,

Would be great to be able to pass a list of repositories to a `Repo` rule for common cleaning rules
For example

```yaml
  policies:
    - name: Remove all empty folders from [repo1, repo2, repo3, repo4]
      rules:
        - rule: Repo
          name:
            - repo1
            - repo2
            - repo3
            - repo4
        - rule: DeleteEmptyFolders
```  

As of now, artifactory-cleanup search for a repository named **[repo1, repo2, repo3, repo4]**

artifactory-cleanup version : 1.0.1

```
********************************************************************************
Verbose MODE
Checking '['repo1', 'repo2', 'repo3', 'repo4']' repository exists.
404 Client Error:  for url: https://example.com/artifactory/api/storage/%5B'repo1',%20'repo2',%20'repo3',%20'repo4'%5D
The ['repo1', 'repo2', 'repo3', 'repo4'] repository does not exist
```

Thanks
Alex

**Comment by allburov** [comment]
Added `RepoList` in `1.0.2`!

```yaml
- rule: RepoList
  repos:
    - repo1
    - repo2
    - repo3
```
