### ISSUE TITLE
KeepLatestNVersionImagesByProperty does not work for multiple images

### ISSUE THREAD

**Issue by kenny-monster** [devopshq/artifactory-cleanup#77]
It seems that its working when only one image is involved. When I include multiple images, it only seems to apply the logic to one of the images:

My policy looks like this:
```
- name: my-policy
      rules:
        - rule: Repo
          name: "my-repo"
        - rule: IncludeDockerImages
          masks:
            - "my-image-1:*"
            - "my-image-2:*"
        - rule: DeleteDockerImagesNotUsed
          days: 60
        - rule: KeepLatestNVersionImagesByProperty
          count: 2
          number_of_digits_in_version: 1
```

Both images have not been used for more than 60 days. Running with either image alone results in the two latest image versions being filtered out as expected.

_Originally posted by @kenny-monster in https://github.com/devopshq/artifactory-cleanup/issues/60#issuecomment-1266444070_
