### ISSUE TITLE
formatting question - KeepLatestVersionNFilesInFolder

### ISSUE THREAD

**Issue by t-readyroc** [devopshq/artifactory-cleanup#83]
I'm wondering if I may not be able to use this tool due to our versioning scheme. Each repo has a "Packages" subfolder that I'm including, but then also has 30+ different file names in each. I've written the equivalent number of rules for each repo, e.g.:

```yaml
        - rule: KeepLatestVersionNFilesInFolder
          count: 2
          custom_regexp: "bootstrap-gui-([\d]+\.[\d]+\-[\d]+).*\.rpm"
        - rule: KeepLatestVersionNFilesInFolder
          count: 2
          custom_regexp: "bootstrap-influxdb-([\d]+\.[\d]+\-[\d]+).*\.rpm"
        - rule: KeepLatestVersionNFilesInFolder
          count: 2
          custom_regexp: "bootstrap-ingest-([\d]+\.[\d]+\-[\d]+).*\.rpm"
        - rule: KeepLatestVersionNFilesInFolder
          count: 2
```

etc & so forth, to cover each of the different file names. However, when I attempt to run the cleanup, the script gives me the error:

```
ValueError: invalid literal for int() with base 10: '6-4'
```

I have tested each individual regex, to make sure that they do match the version numbers for each file name. I'm pretty sure I'm just not formatting it correctly for what the script expects. I'm guessing that maybe the rule separates the digits by dots? Which won't work for us, since our last digit is separated by a dash?

Any guidance would be appreciated.

**Comment by allburov** [comment]
Hi! 

Have you tried to escape `\` with `\\`?
The example from the readme.md shows it as:

```yaml
- rule: KeepLatestVersionNFilesInFolder
  count: 1
  custom_regexp: "[^\\d][\\._]((\\d+\\.)+\\d+)"
```

Could you give few examples for the filenames? I need to reproduce it on my side, don't get the filename format from the regexp

**Comment by allburov** [comment]
Do you use RPM repository or it's just usual file one with rpm files in it? 
Asking because Artifactory set some additional properties to the files in RPM repository and it can help us in the future research if above solution doesn't work.

**Comment by t-readyroc** [comment]
Sorry, yes, I ran into the double escape issue, & have since updated the regexp:

```yaml
        - rule: KeepLatestVersionNFilesInFolder
          count: 2
          custom_regexp: "bootstrap-gui-([\\d]+\\.[\\d]+\\-[\\d]+).*\\.rpm"
        - rule: KeepLatestVersionNFilesInFolder
          count: 2
          custom_regexp: "bootstrap-influxdb-([\\d]+\\.[\\d]+\\-[\\d]+).*\\.rpm"
        - rule: KeepLatestVersionNFilesInFolder
          count: 2
          custom_regexp: "bootstrap-ingest-([\\d]+\\.[\\d]+\\-[\\d]+).*\\.rpm"
```

The repositories are "package type: RPM," & examples of the files above are:

```
bootstrap-gui-3.10-33.src.rpm
bootstrap-ingest-3.10-92.src.rpm
bootstrap-influxdb-3.7-3.noarch.rpm
```

As you can see, the revision is delineated by a `-`, which is what, I think is causing the issue. I found yesterday where it looks like [the rule](https://github.com/devopshq/artifactory-cleanup/blob/f06b2afc44cd82d65d62cd28c712c74e1ee45201/artifactory_cleanup/rules/keep.py#L177) is splitting on `.`

**Comment by allburov** [comment]
@t-readyroc thank you for pointing out the exact line!

I've pushed the fix for it here https://github.com/devopshq/artifactory-cleanup/pull/84
Could you install from the branch and test that it works for your case? If it does - I'll release changes

```
pip install git+https://github.com/devopshq/artifactory-cleanup.git@keep-latest-n-files-no-dot
artifactory-cleanup --version
# Must show 1.0.4
```

**Important note** - above rules don't work in that way

If you use ` "bootstrap-ingest-([\\d]+\\.[\\d]+\\-[\\d]+).*\\.rpm"` regexp - the rule will keep all artifacts that doesn't match the rule (just to avoid accidental removes for new artifacts)

In order to achieve what you want - you have to split it to different policies
```yaml
  policies:
    - name: reponame - bootstrap gui
      rules:
        - rule: Repo
          name: "reponame"
        - rule: KeepLatestVersionNFilesInFolder
          count: 2
          custom_regexp: "bootstrap-gui-([\\d]+\\.[\\d]+\\-[\\d]+).*\\.rpm"
    - name: reponame - bootstrap ingest
      rules:
        - rule: Repo
          name: "reponame"
        - rule: KeepLatestVersionNFilesInFolder
          count: 2
          custom_regexp: "bootstrap-ingest-([\\d]+\\.[\\d]+\\-[\\d]+).*\\.rpm"

```
