### ISSUE TITLE
Formatting Question - RepoList

### ISSUE THREAD

**Issue by NFerrovia** [devopshq/artifactory-cleanup#87]
Hello! Thank you for your hard work on this tool!
I have a question regarding RepoList, i can't seem to get it to work unlike the normal Repo & Name rule.

The instructions read as follow:

```yaml
- rule: RepoList
  repos:
    - repo1
    - repo2
    - repo3
```
    
my code reads as follows:

```yaml
      - rule: RepoList
          repos: 
            - repo1
            - repo2
        - rule: DeleteEmptyFolders
```

And i am getting the following error:

```
'NoneType' object has no attribute 'get'
```

**Comment by allburov** [comment]
Could you get a full yaml configuration and the full traceback? You can remove your private data there

**Comment by NFerrovia** [comment]
Sure, here's also the code running as intended on the normal repo & name config.

```yaml
artifactory-cleanup:
  server: $ARTIFACTORY_SERVER
  user: $ARTIFACTORY_USERNAME
  password: $ARTIFACTORY_PASSWORD

  policies:
    - name: Remove all empty folders from repo1 
      rules:
        - rule: Repo
          name: "repo1"
        - rule: DeleteOlderThan
          days: 7
```

Which works as intended as seen here:

```yaml
+----------------------------------------------------+-------------+------+
| Cleanup Policy                                     | Files count | Size |
+----------------------------------------------------+-------------+------+
| Remove all empty folders from ba-core-docker-local |    16474    | 299G |
|                                                    |             |      |
| Total size: 299G                                   |             |      |
+----------------------------------------------------+-------------+------+
```

But when i utilize Repolist:

```yaml
artifactory-cleanup:
  server: $ARTIFACTORY_SERVER
  user: $ARTIFACTORY_USERNAME
  password: $ARTIFACTORY_PASSWORD

  policies:
    - name: Delete empty folders from [repo1, repo2, repo3]
      rules:
        - rule: RepoList
          repos:
            - repo1
            - repo2
            - repo3
        - rule: DeleteEmptyFolders
 ```
 I get the aforementioned unceremonious error no traceback:
 
 ```yaml
$ artifactory-cleanup
********************************************************************************
Verbose MODE
Checking 'repo1' repository exists.
Check failed for rule 'RepoList' in policy 'Delete empty folders from [repo1, repo2, repo3]':
'NoneType' object has no attribute 'get'
```

Which leads me to believe i have a formatting error, but this is what i gathered from the instructions.
I've tried different configurations but since i can't find a proper example on repoList i thought i'd open this issue with this question.
